sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t gregbarbosa103/docker-react -f Docerfile.dev .

script:
  - docker run -e CI=true gregbarbosa103/docker-react npm run test -- --coverage
